#!/bin/bash/
# This script lets you initialize a new project workspace with your libft, 
# ft_printf and other useful directories
# usage : 
# sh 03 <project name> <libft folder path> <ft_printf folder path> <username>

if [ $# -ne 4 ]; then
    echo "usage : 
    sh 03 <project name> <libft folder path> <ft_printf folder path> <username>"
else
    REPO_NAME=$1
    LIBFT=$2
    FT_PRINTF=$3
    AUTHOR=$4
    # init 
    curl -u $AUTHOR https://api.github.com/user/repos -d\
        "{\"name\":\"$REPO_NAME\"}"
    git clone https://github.com/$AUTHOR/$REPO_NAME.github
    # init project
    cp -a $LIBFT $REPO_NAME/libft
    cp -a $FT_PRINTF $REPO_NAME/ft_printf
    rm -rf $REPO_NAME/ft_printf/libft
    sed 's/..\/libft\/libft.h/..\/..\/libft\/libft.h/g'\
        $REPO_NAME/ft_printf/src/ft_printf.h >\
        $REPO_NAME/ft_printf/src/ft_printf1.h
    rm $REPO_NAME/ft_printf/src/ft_printf.h
    rm $REPO_NAME/ft_printf/README.md
    rm $REPO_NAME/ft_printf/author
    rm $REPO_NAME/libft/author
    rm -rf $REPO_NAME/libft/.git
    rm -rf $REPO_NAME/ft_printf/.git
    find $REPO_NAME -name \*.DS_Store -type f -delete
    mv  $REPO_NAME/ft_printf/src/ft_printf1.h\
        $REPO_NAME/ft_printf/src/ft_printf.h
    mkdir $REPO_NAME/src
    mkdir $REPO_NAME/include
    touch $REPO_NAME/src/$REPO_NAME.h
    # touch $REPO_NAME/Makefile
    DATE=$(date "+%Y/%m/%d")
    TIME=$(date "+%T")
    # echo $DATE
    echo "# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: $AUTHOR <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: $DATE $TIME by $AUTHOR          #+#    #+#              #
#    Updated: $DATE $TIME by $AUTHOR         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #" > $REPO_NAME/Makefile
    echo $AUTHOR > $REPO_NAME/author
    # init git repo
    # git init
    cd $REPO_NAME
    git add -A
    git commit -m "init repo"
    git push
    cd ..
fi